name: my-workflow
on: workflow_dispatch
jobs:
  job-one:
   runs-on: ubuntu-latest
   steps:
    - name: First Step Run
      run: echo 'First Step !'
    - name: Second Step Run
      run: echo 'Second Step !'
    - name: Final Step Run
      run: |
            echo 'This is'
            echo 'Final Step'
  
